FROM ubuntu:14.04
MAINTAINER Allen Yu "mail@allenyu.info"

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-libxml2 \
    python-pip \
    python-pycurl \
    python-virtualenv \
    python-software-properties \
    sudo \
    vim-nox \
    zip \
    gfortran \
    libxml2 \
    libxml2-dev \
    libmemcached-dev \
    autotools-dev  \
    zlib1g-dev \
